#!/usr/bin/env bash
set -euo pipefail

NIX_FILE="$BUILDKITE_PLUGIN_NIX_BUILDKITE_FILE"
if [[ -n "${BUILDKITE_PLUGIN_NIX_BUILDKITE_POST_BUILD_HOOK:-}" ]]; then
    export POST_BUILD_HOOK="$BUILDKITE_PLUGIN_NIX_BUILDKITE_POST_BUILD_HOOK"
    echo "POST_BUILD_HOOK is $POST_BUILD_HOOK"
else
    echo "No post build hook set."
fi

echo "--- :nixos: Running nix-buildkite"
nix-build -E '(import "${ builtins.fetchGit { url = https://github.com/hackworthltd/nix-buildkite-buildkite-plugin; ref = "hackworthltd-v3"; } }/jobs.nix").nix-buildkite' -o nix-buildkite
PIPELINE=$( ./nix-buildkite/bin/nix-buildkite "$NIX_FILE" )
rm nix-buildkite

echo "--- :pipeline: Uploading pipeline"
echo "$PIPELINE" | buildkite-agent pipeline upload
